language: cpp
script: make
compiler:
  #- clang Problems with crypto++ 5.6.1
  - gcc
before_script:
  - cd bin
  - cmake ../
before_install:
  #- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  #- sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
  - sudo apt-get update
install:
  #- sudo apt-get install clang-3.4
  - sudo apt-get install libgmp3-dev
  - sudo apt-get install trousers libtspi-dev
  - sudo apt-get install cmake
  - sudo apt-get install libcrypto++9 libcrypto++9-dbg libcrypto++-dev
  - sudo apt-get install libblkid-dev
  - sudo apt-get install libgtest-dev
  - sudo pip install cpp-coveralls --use-mirrors
after_success:
  - coveralls --verbose --exclude CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp
